### ISSUE TITLE
The app on iOS is not in full screen

### ISSUE THREAD

**Issue by ZenCocoon** [BookingSync/smily-mobile-app#3]
We need to ensure the app is loaded in full screen as this does not look nice.

![IMG_4025](https://user-images.githubusercontent.com/10502/152540002-19a0cf28-3c2c-4981-a5e5-df7079b2ed97.PNG)

@EroMCakes Did you test on Android ones with rounded screens to see if full screen as well?

**Comment by EroMCakes** [comment]
It is in full screen. I even ensured it's wrapped with a safe area so it won't go under notification bar here's a screen from my phone. Though I thing there's gotta be some tweaking on the website responsiveness part for some panels like the conversations. ![Screenshot_20220204-145710.jpg](https://user-images.githubusercontent.com/44838692/152541344-af398533-6558-43f4-8f81-b2864a17de73.jpg)

**Comment by ZenCocoon** [comment]
hmm, actually I'd like the rendering to go under the notifications, to really use the entire display on the top and bottom. We will then add margins as needed on the web side.

**Comment by EroMCakes** [comment]
![image](https://user-images.githubusercontent.com/44838692/152549885-cc4bd3fe-d1ac-407a-8f5b-3e7ba16dde19.png)
Is this appropriate? I can also if you want make sure the whole status bar is hidden until you swipe down.

**Comment by ZenCocoon** [comment]
The last one is great, we will adjust on the web side.

**Comment by ZenCocoon** [comment]
ok, all good now.
